apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: fauzigalih/simplejob
              imagePullPolicy: IfNotPresent
              #resources: {}
          restartPolicy: OnFailure
