apiVersion: v1
kind: Pod
metadata:
  name: nama-metadata
spec:
  containers:
    - name: nama-container
      image: nama-image
      ports:
        - containerPort: port-container
  nodeSelector:
    node: nama-selector-node
    zona: nama-selector-zona