apiVersion: v1
kind: Pod
metadata:
  name: nginx-label
  labels:
    environment: staging
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
      - containerPort: 80