apiVersion: v1
kind: Pod
metadata:
  name: nginx-selector
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
  nodeSelector:
    node: node-agent1
    zona: zona-jakarta