apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: fauzigalih/hello:normal
        ports:
          - containerPort: 3000
---
# ini service tipe Headless
apiVersion: v1
kind: Service 
metadata:
  name: hello-service
spec:
  clusterIP: None
  selector:
    app: hello-world
  ports: 
    - name: hello-headless-service
      port: 8080 # Service Port
      targetPort: 8080 # Container Port

## VERY IMPORTANT NODE
# 1. When using Headless Service, we should use both the  "Service Port and Target Port" same. 
# 2. Headless Service directly sends traffic to Pod with Pod IP and Container Port. 
# 3. DNS resolution directly happens from headless service to Pod IP.