apiVersion: batch/v1
kind: Job
metadata:
  name: node-job
spec:
  completions: 12
  parallelism: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: nodejs
          image: fauzigalih/node-job
