apiVersion: v1
kind: Service
metadata:
  name: nama-service
spec:
  type: NodePort
  selector:
    app: nama-app
  ports:
    - protocol: TCP
      port: port-service
      targetPort: port-target
      nodePort: port-node
