apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nama-replica-set
spec:
  replicas: 3   # jumlah replica pod
  selector:
    matchLabels:   # selector replica set
      label-key1: label-value1
  template:
    metadata:
      name: nama-pod
      labels:    # label harus sama dengan selector replica set
        label-key1: label-value1
    spec:
      containers:
        - name: nama-container
          image: nama-image
          ports:
            - containerPort: 80   # port container