apiVersion: v1
kind: Namespace
metadata:
  name: teknologi

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-namespace
  namespace: teknologi
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
