apiVersion: v1
kind: Pod
metadata:
  name: nginx-annotations
  annotations:
    desc: "Ini contoh penggunaan Annotation"
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80