apiVersion: v1
kind: Namespace
metadata:
  name: typesense

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: typesense-configmap
  namespace: typesense
data:
  nodes: "typesense-0.ts.typesense.svc.cluster.local:8107:8108,typesense-1.ts.typesense.svc.cluster.local:8107:8108,typesense-2.ts.typesense.svc.cluster.local:8107:8108"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: typesense-statefulset
  namespace: typesense
spec:
  selector:
    matchLabels:
      app: typesense
  serviceName: typesense-service
  replicas: 3
  template:
    metadata:
      labels:
        app: typesense
    spec:
      containers:
      - name: typesense
        image: typesense/typesense:0.25.1
        ports:
        - containerPort: 8108
          name: http
        volumeMounts:
        #- name: typesense-configmap
        #  mountPath: /usr/share/typesense
        - name: typesense-pvc
          mountPath: /usr/share/typesense/data
  volumeClaimTemplates:
  - metadata:
      name: typesense-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: typesense-pv
  namespace: typesense
spec:
  capacity:
    storage: 35Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./

---

apiVersion: v1
kind: Service
metadata:
  name: typesense-service
  namespace: typesense
spec:
  type: NodePort
  selector:
    app: typesense
  ports:
    - protocol: TCP
      port: 8108
      targetPort: 8108
      nodePort: 30001
